html-skeleton/.npmrc
html-skeleton/index.html

html-skeleton - Chase Simmonds

---

html-syntax/.npmrc
html-syntax/index.html

html-syntax - Chase Simmonds

---

html-block-and-inline/.npmrc
html-block-and-inline/index.html

html-block-and-inline - Chase Simmonds

---

html-lists/.npmrc
html-lists/index.html

html-lists - Chase Simmonds

---

html-links/.npmrc
html-links/index.html

html-links - Chase Simmonds

---

html-forms/.npmrc
html-forms/index.html

html-forms - Chase Simmonds

---

html-tables/.npmrc
html-tables/index.html

html-tables - Chase Simmonds

---

css-syntax/.npmrc
css-syntax/index.html
css-syntax/styles.css

css-syntax - Chase Simmonds

---

css-colors/.npmrc
css-colors/index.html
css-colors/styles.css

css-colors - Chase Simmonds

---

css-box-model/.npmrc
css-box-model/index.html
css-box-model/styles.css

css-box-model - Chase Simmonds

---

css-pseudo-classes/.npmrc
css-pseudo-classes/index.html
css-pseudo-classes/styles.css

css-pseudo-classes - Chase Simmonds

---

css-fonts/.npmrc
css-fonts/.stylelintrc
css-fonts/index.html
css-fonts/styles.css

css-fonts - Chase Simmonds

---

javascript-primitives-and-variables/.eslintrc
javascript-primitives-and-variables/.npmrc
javascript-primitives-and-variables/index.html
javascript-primitives-and-variables/main.js

javascript-primitives-and-variables - Chase Simmonds

---

javascript-operators-and-expressions/.eslintrc
javascript-operators-and-expressions/.npmrc
javascript-operators-and-expressions/index.html
javascript-operators-and-expressions/main.js

javascript-operators-and-expressions - Chase Simmonds

---

javascript-objects/.eslintrc
javascript-objects/.npmrc
javascript-objects/index.html
javascript-objects/main.js

javascript-objects - Chase Simmonds

---

javascript-arrays/.eslintrc
javascript-arrays/.npmrc
javascript-arrays/index.html
javascript-arrays/main.js

javascript-arrays - Chase Simmonds

---

javascript-functions/.eslintrc
javascript-functions/.npmrc
javascript-functions/index.html
javascript-functions/main.js

javascript-functions - Chase Simmonds

---

javascript-methods/.eslintrc
javascript-methods/.npmrc
javascript-methods/index.html
javascript-methods/main.js

javascript-methods - Chase Simmonds

---

javascript-loops/.eslintrc
javascript-loops/.npmrc
javascript-loops/index.html
javascript-loops/main.js

javascript-loops - Chase Simmonds

---

javascript-loops-practice/.eslintrc
javascript-loops-practice/.npmrc
javascript-loops-practice/add-suffix-to-all.js
javascript-loops-practice/add-suffix-to-all.test.js
javascript-loops-practice/countdown.js
javascript-loops-practice/countdown.test.js
javascript-loops-practice/filter-out-nulls.js
javascript-loops-practice/filter-out-nulls.test.js
javascript-loops-practice/filter-out-strings.js
javascript-loops-practice/filter-out-strings.test.js
javascript-loops-practice/find-index.js
javascript-loops-practice/find-index.test.js
javascript-loops-practice/get-indexes.js
javascript-loops-practice/get-indexes.test.js
javascript-loops-practice/get-student-names.js
javascript-loops-practice/get-student-names.test.js
javascript-loops-practice/includes-seven.js
javascript-loops-practice/includes-seven.test.js
javascript-loops-practice/index.html
javascript-loops-practice/odd-or-even.js
javascript-loops-practice/odd-or-even.test.js
javascript-loops-practice/sum-all.js
javascript-loops-practice/sum-all.test.js

javascript-loops-practice - Chase Simmonds

---

dom-events/.eslintrc
dom-events/.npmrc
dom-events/buttons.html
dom-events/buttons.js
dom-events/document.html
dom-events/document.js
dom-events/styles.css

dom-events - Chase Simmonds

---

dom-manipulation/.npmrc
dom-manipulation/index.html
dom-manipulation/main.js
dom-manipulation/styles.css

dom-manipulation - Chase Simmonds

---

javascript-light-bulb/.npmrc
javascript-light-bulb/index.html
javascript-light-bulb/main.js
javascript-light-bulb/styles.css

javascript-light-bulb - Chase Simmonds

---

string-manipulation-1/.eslintrc
string-manipulation-1/.npmrc
string-manipulation-1/index.html
string-manipulation-1/src/ban-methods.js
string-manipulation-1/src/capitalize.js
string-manipulation-1/src/capitalize.test.js
string-manipulation-1/src/get-first-char.js
string-manipulation-1/src/get-first-char.test.js
string-manipulation-1/src/get-last-char.js
string-manipulation-1/src/get-last-char.test.js
string-manipulation-1/src/get-words.js
string-manipulation-1/src/get-words.test.js
string-manipulation-1/src/is-lower-cased.js
string-manipulation-1/src/is-lower-cased.test.js
string-manipulation-1/src/is-upper-cased.js
string-manipulation-1/src/is-upper-cased.test.js
string-manipulation-1/src/is-vowel.js
string-manipulation-1/src/is-vowel.test.js
string-manipulation-1/src/reverse-word.js
string-manipulation-1/src/reverse-word.test.js

string-manipulation-1 - Chase Simmonds

---

array-manipulation-1/.eslintrc
array-manipulation-1/.npmrc
array-manipulation-1/index.html
array-manipulation-1/src/ban-methods.js
array-manipulation-1/src/compact.js
array-manipulation-1/src/compact.test.js
array-manipulation-1/src/head.js
array-manipulation-1/src/head.test.js
array-manipulation-1/src/initial.js
array-manipulation-1/src/initial.test.js
array-manipulation-1/src/last.js
array-manipulation-1/src/last.test.js
array-manipulation-1/src/reverse.js
array-manipulation-1/src/reverse.test.js
array-manipulation-1/src/tail.js
array-manipulation-1/src/tail.test.js

array-manipulation-1 - Chase Simmonds

---

object-manipulation-1/.eslintrc
object-manipulation-1/.npmrc
object-manipulation-1/index.html
object-manipulation-1/src/ban-methods.js
object-manipulation-1/src/get-keys.js
object-manipulation-1/src/get-keys.test.js
object-manipulation-1/src/get-value.js
object-manipulation-1/src/get-value.test.js
object-manipulation-1/src/get-values.js
object-manipulation-1/src/get-values.test.js
object-manipulation-1/src/set-value.js
object-manipulation-1/src/set-value.test.js
object-manipulation-1/src/to-object.js
object-manipulation-1/src/to-object.test.js

object-manipulation-1 - Chase Simmonds

---

javascript-forms/.eslintrc
javascript-forms/.npmrc
javascript-forms/form-events.html
javascript-forms/form-events.js
javascript-forms/form-values.html
javascript-forms/form-values.js
javascript-forms/styles.css

javascript-forms - Chase Simmonds

---

dom-event-delegation/.eslintrc
dom-event-delegation/.npmrc
dom-event-delegation/index.html
dom-event-delegation/main.js
dom-event-delegation/styles.css

dom-event-delegation - Chase Simmonds

---

dom-event-delegation/.eslintrc
dom-event-delegation/.npmrc
dom-event-delegation/index.html
dom-event-delegation/main.js
dom-event-delegation/styles.css

dom-events-delegation - Chase Simmonds

---

javascript-and-json/.eslintrc
javascript-and-json/.npmrc
javascript-and-json/index.html
javascript-and-json/main.js

javascript-and-json - Chase Simmonds

---

javascript-typing-tutor/.npmrc
javascript-typing-tutor/index.html
javascript-typing-tutor/main.js
javascript-typing-tutor/styles.css

https://user-images.githubusercontent.com/65789518/170915529-89c89801-4198-4ebe-a892-e1d5d69bd229.mov

javascript-typing-tutor - Chase Simmonds

---

javascript-modal/.npmrc
javascript-modal/index.html
javascript-modal/main.js
javascript-modal/styles.css

https://user-images.githubusercontent.com/65789518/170768500-070333a0-0863-46bc-8a82-83efb66513d1.mov

javascript-modal - Chase Simmonds

---

javascript-constructors/.eslintrc
javascript-constructors/.npmrc
javascript-constructors/example-constructor.html
javascript-constructors/example-constructor.js
javascript-constructors/index.html
javascript-constructors/new-objects.html
javascript-constructors/new-objects.js
javascript-constructors/stopwatch.html
javascript-constructors/stopwatch.js
javascript-constructors/student.js
javascript-constructors/student.test.js
javascript-constructors/test.html

javascript-constructors - Chase Simmonds

---

javascript-timers/.npmrc
javascript-timers/interval.html
javascript-timers/interval.js
javascript-timers/timeout.html
javascript-timers/timeout.js

https://user-images.githubusercontent.com/65789518/172695341-a6bcabfa-4a4b-45ff-a065-be68568310a8.mov

javascript-timers - Chase Simmonds

---

javascript-bank/.eslintrc
javascript-bank/.npmrc
javascript-bank/account.js
javascript-bank/account.test.js
javascript-bank/bank.js
javascript-bank/bank.test.js
javascript-bank/index.html
javascript-bank/test.html
javascript-bank/transaction.js
javascript-bank/transaction.test.js

javascript-bank - Chase Simmonds

---

es6-destructuring/.eslintrc
es6-destructuring/.npmrc
es6-destructuring/index.html
es6-destructuring/main.js

es6-destructuring - Chase Simmonds

---

node-intro/.eslintrc
node-intro/.npmrc
node-intro/hello-node.js

node-intro - Chase Simmonds

---

node-process-argv/.eslintrc
node-process-argv/.npmrc
node-process-argv/all-arguments.js
node-process-argv/echo.js
node-process-argv/process.js

node-process-argv - Chase Simmonds

---

node-module-system/.eslintrc
node-module-system/.npmrc
node-module-system/a-wrapped-module.js

node-module-system - Chase Simmonds

---

node-require/.eslintrc
node-require/.npmrc
node-require/add.js
node-require/calculate.js
node-require/divide.js
node-require/multiply.js
node-require/subtract.js

node-require - Chase Simmonds

---

the-event-loop/.eslintrc
the-event-loop/.npmrc
the-event-loop/interval.js
the-event-loop/timeout.js

https://user-images.githubusercontent.com/65789518/176559364-e76c7941-9a85-40c9-b98f-e651e3a2e1e4.mov

the-event-loop - Chase Simmonds

---

node-notes-cli/.eslintrc
node-notes-cli/.npmrc
node-notes-cli/app.js
node-notes-cli/data.json

node-notes-cli - Chase Simmonds

---

npm-intro/.npmrc
npm-intro/package.json

npm-intro - Chase Simmonds

---

express-intro/.npmrc
express-intro/index.js
express-intro/package.json

express-intro - Chase Simmonds

---

express-hello-world/.npmrc
express-hello-world/index.js
express-hello-world/package.json

express-hello-world - Chase Simmonds

---

postgres-intro/.npmrc
postgres-intro/list-of-databases.txt

postgres-intro - Chase Simmonds

---

express-delete/.npmrc
express-delete/index.js
express-delete/package.json

express-delete - Chase Simmonds

---

express-get-json/.npmrc
express-get-json/index.js
express-get-json/package.json

express-get-json - Chase Simmonds

---

sql-select/.npmrc
sql-select/actor-forty.sql
sql-select/actors-names.sql
sql-select/all-actors.sql
sql-select/all-customers.sql
sql-select/all-films.sql
sql-select/all-genres.sql
sql-select/all-languages.sql
sql-select/cheap-to-rent.sql
sql-select/expensive-films.sql
sql-select/five-customer-emails.sql
sql-select/inactive-customers.sql
sql-select/r-rated-films.sql
sql-select/second-store-customers.sql
sql-select/ten-actor-first-names.sql
sql-select/twenty-films-of-06.sql
sql-select/two-kilmers.sql
sql-select/west-bengali-postal-codes.sql

sql-select - Chase Simmonds

---

sql-update/.npmrc
sql-update/make-yoder.sql
sql-update/murica.sql
sql-update/sick-prank.sql

sql-update - Chase Simmonds

---

sql-insert/.npmrc
sql-insert/insert-actor.sql
sql-insert/insert-languages.sql

sql-insert - Chase Simmonds

---

es6-promises/.eslintrc
es6-promises/.npmrc
es6-promises/index.js
es6-promises/take-a-chance.js

es6-promises - Chase Simmonds

---

sgt-back-end/.npmrc
sgt-back-end/data.sql
sgt-back-end/index.js
sgt-back-end/package.json
sgt-back-end/schema.sql

sgt-back-end - Chase Simmonds

---

array-filter/.eslintrc
array-filter/.npmrc
array-filter/index.html
array-filter/main.js

array-filter - Chase Simmonds

---

array-map/.eslintrc
array-map/.npmrc
array-map/index.html
array-map/main.js
array-map/map.js

array-map - Chase Simmonds

---

array-reduce/.eslintrc
array-reduce/.npmrc
array-reduce/index.html
array-reduce/main.js
array-reduce/reduce.js

array-reduce - Chase Simmonds

---

array-reduce/main.js
es6-classes/.eslintrc
es6-classes/.npmrc
es6-classes/example-class.html
es6-classes/example-class.js
es6-classes/stopwatch.html
es6-classes/stopwatch.js
es6-classes/student.js
es6-classes/student.test.js
es6-classes/test.html

es6-classes - Chase Simmonds

---

react-events-and-state/.gitignore
react-events-and-state/.npmrc
react-events-and-state/dist/index.html
react-events-and-state/package.json
react-events-and-state/src/index.jsx
react-events-and-state/webpack.config.js

https://user-images.githubusercontent.com/65789518/178891457-b3ec6196-77c8-4dfa-b246-b2f82ae691e2.mov

react-events-and-state - Chase Simmonds

---

fetch/.eslintrc
fetch/.npmrc
fetch/index.html
fetch/main.js

fetch - Chase Simmonds

---

api-authentication/.env.example
api-authentication/.eslintrc
api-authentication/.gitignore
api-authentication/.npmrc
api-authentication/create-token.js
api-authentication/database/data.sql
api-authentication/database/schema.sql
api-authentication/package.json
api-authentication/scripts/db-import.bash
api-authentication/server/client-error.js
api-authentication/server/error-middleware.js
api-authentication/server/index.js
api-authentication/verify-password.js

api-authentication - Chase Simmonds

---

api-authorization/.env.example
api-authorization/.eslintrc
api-authorization/.gitignore
api-authorization/.npmrc
api-authorization/database/data.sql
api-authorization/database/schema.sql
api-authorization/package.json
api-authorization/scripts/db-import.bash
api-authorization/server/authorization-middleware.js
api-authorization/server/client-error.js
api-authorization/server/error-middleware.js
api-authorization/server/index.js
api-authorization/verify-token.js

api-authorization - Chase Simmonds

---

javascript-closures/.eslintrc
javascript-closures/.npmrc
javascript-closures/index.html
javascript-closures/main.js
javascript-closures/make-adder.html
javascript-closures/make-counter.html
javascript-closures/make-sizer.html

javascript-closures - Chase Simmonds
